server:
  port: 8081
spring:
  application:
    name: mobile
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/docker?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai